#version 430 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
layout(rgba32f, binding = 0) uniform image3D imgOutput;


void main() {
    vec4 value = vec4(0.0, 0.0, 0.0, 1.0);
    vec3 texelCoord = gl_GlobalInvocationID.xyz;
	
    value.x = texelCoord.x / gl_NumWorkGroups.x / gl_WorkGroupSize.x;
    value.y = texelCoord.y / gl_NumWorkGroups.y / gl_WorkGroupSize.y;
	value.z = texelCoord.z / gl_NumWorkGroups.z / gl_WorkGroupSize.z;

    imageStore(imgOutput, ivec3(texelCoord), value);
}
